collections:
  - name: artists
    label: Featured Artists
    folder: data/campaigns
    create: true
    fields: 
      - { label: "Artist Name", name: "artist_name", widget: "string" }
      - { label: "Intro Bio", name: "intro", widget: "text" }  # Textarea for short bio
      - { label: "Instagram Link", name: "instagram_link", widget: "string" }
      - { label: "Picture", name: "picture", widget: "image" }
